INHERIT: ./docs/env

theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest 
  icon: 
    repo: fontawesome/brands/git
  logo: logo.png
  favicon: https://konsilion.fr/wp/wp-content/uploads/2022/03/Logo_Konsilion_1.png

plugins:
  - macros
  - search
  - mike

markdown_extensions:
  - toc:
      permalink: true
  - md_in_html
  - footnotes
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra_css:
  - _css/extra.css