INHERIT: ./docs/env

theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - navigation.tracking
    
  logo: ./images/logo.png
  favicon: https://konsilion.fr/wp/wp-content/uploads/2022/03/Logo_Konsilion_1.png


plugins:
  - macros
  - search
  - mike



markdown_extensions:
  - toc:
      permalink: true
  - md_in_html
  - footnotes
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets


extra_css:
  - https://konsilion.github.io/katalog-setup/css/extra.css


